### ISSUE TITLE
RunConfig TimeoutInSeconds should not be required

### ISSUE THREAD

**Issue by flochaz** [aws-cloudformation/aws-cloudformation-resource-providers-synthetics#31]
From what says the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-synthetics-canary-runconfig.html#aws-properties-synthetics-canary-runconfig-properties), `TimeoutInSeconds` should not be required since a default behavior seems implemented on service side: 

> **TimeoutInSeconds**
> How long the canary is allowed to run before it must stop. You can't set this time to be longer than the frequency of the runs of this canary.
> 
> **If you omit this field**, the frequency of the canary is used as this value, up to a maximum of 900 seconds.
> 
> Required: **Yes**

**Comment by PatMyron** [comment]
fixed in https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-synthetics/pull/32
